package com.chromamon.analysis.constants;

public enum TransformerTypeEnum {
    STEP_UP, STEP_DOWN, POWER_TRANSFORMER, DISTRIBUTION_TRANSFORMER, ISOLATING_TRANSFORMER, AUTO_TRANSFORMER,
    PHASE_ADJUSTING_TRANSFORMER, REGULATION_TRANSFORMER, GROUND_TRANSFORMER
}
